"""add fridge input item stock link

Revision ID: 5e2a029d2b02
Revises: 7db1aa7c5f21
Create Date: 2026-08-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2a029d2b02'
down_revision: Union[str, Sequence[str], None] = '7db1aa7c5f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###
    # Nullable, no server default needed: existing `fridge_input_item` rows
    # predate the persistent fridge stock and simply have no linked stock
    # item (see `FridgeInputItem.fridge_stock_item_id`'s docstring).
    with op.batch_alter_table('fridge_input_item') as batch_op:
        batch_op.add_column(sa.Column('fridge_stock_item_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f('ix_fridge_input_item_fridge_stock_item_id'),
            ['fridge_stock_item_id'],
            unique=False,
        )
        batch_op.create_foreign_key(
            'fk_fridge_input_item_fridge_stock_item_id',
            'fridge_stock_item',
            ['fridge_stock_item_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###
    with op.batch_alter_table('fridge_input_item') as batch_op:
        batch_op.drop_constraint('fk_fridge_input_item_fridge_stock_item_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_fridge_input_item_fridge_stock_item_id'))
        batch_op.drop_column('fridge_stock_item_id')
    # ### end Alembic commands ###
