"""add fridge stock item

Revision ID: 7db1aa7c5f21
Revises: ffd7922d8ec7
Create Date: 2026-08-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7db1aa7c5f21'
down_revision: Union[str, Sequence[str], None] = 'ffd7922d8ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fridge_stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_stock_item_ingredient_name'), 'fridge_stock_item', ['ingredient_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_stock_item_ingredient_name'), table_name='fridge_stock_item')
    op.drop_table('fridge_stock_item')
    # ### end Alembic commands ###
