"""add suggestion used stock item ids

Revision ID: 851360932c2a
Revises: 5e2a029d2b02
Create Date: 2026-08-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '851360932c2a'
down_revision: Union[str, Sequence[str], None] = '5e2a029d2b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: needs a server
    # default so `ADD COLUMN ... NOT NULL` doesn't fail against a SQLite
    # file with existing `suggestion` rows — same treatment `phase` got on
    # `agent_run` in ffd7922d8ec7. Pre-existing suggestions predate stock
    # deduction and reported using nothing from the (nonexistent, at the
    # time) persistent stock, so an empty JSON list is the correct value,
    # not just a placeholder. ###
    op.add_column(
        'suggestion',
        sa.Column(
            'used_stock_item_ids_json',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='[]',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('suggestion', 'used_stock_item_ids_json')
    # ### end Alembic commands ###
