"""initial schema

Revision ID: d3aa8367395f
Revises: 
Create Date: 2026-08-26 15:32:46.031868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3aa8367395f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergy_ingredient_name'), 'allergy', ['ingredient_name'], unique=False)
    op.create_table('fridge_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('free_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_note_created_at'), 'preference_note', ['created_at'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('openrouter_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_salt', sa.LargeBinary(), nullable=False),
    sa.Column('password_verifier', sa.LargeBinary(), nullable=False),
    sa.Column('openrouter_api_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fridge_input_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messages_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pending_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['fridge_input_id'], ['fridge_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_fridge_input_id'), 'agent_run', ['fridge_input_id'], unique=False)
    op.create_table('fridge_input_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fridge_input_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['fridge_input_id'], ['fridge_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_input_item_fridge_input_id'), 'fridge_input_item', ['fridge_input_id'], unique=False)
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fridge_input_id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fridge_input_id'], ['fridge_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_created_at'), 'meal_plan', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_plan_fridge_input_id'), 'meal_plan', ['fridge_input_id'], unique=False)
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('allergy_check_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_meal_plan_id'), 'suggestion', ['meal_plan_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suggestion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_suggestion_meal_plan_id'), table_name='suggestion')
    op.drop_table('suggestion')
    op.drop_index(op.f('ix_meal_plan_fridge_input_id'), table_name='meal_plan')
    op.drop_index(op.f('ix_meal_plan_created_at'), table_name='meal_plan')
    op.drop_table('meal_plan')
    op.drop_index(op.f('ix_fridge_input_item_fridge_input_id'), table_name='fridge_input_item')
    op.drop_table('fridge_input_item')
    op.drop_index(op.f('ix_agent_run_fridge_input_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_table('vault')
    op.drop_table('settings')
    op.drop_index(op.f('ix_preference_note_created_at'), table_name='preference_note')
    op.drop_table('preference_note')
    op.drop_table('fridge_input')
    op.drop_index(op.f('ix_allergy_ingredient_name'), table_name='allergy')
    op.drop_table('allergy')
    # ### end Alembic commands ###
