"""add merge dismissal

Revision ID: d769c4fc8f89
Revises: 851360932c2a
Create Date: 2026-08-29 08:04:49.327395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd769c4fc8f89'
down_revision: Union[str, Sequence[str], None] = '851360932c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_dismissal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_a', 'name_b', name='uq_merge_dismissal_pair')
    )
    op.create_index(op.f('ix_merge_dismissal_name_a'), 'merge_dismissal', ['name_a'], unique=False)
    op.create_index(op.f('ix_merge_dismissal_name_b'), 'merge_dismissal', ['name_b'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merge_dismissal_name_b'), table_name='merge_dismissal')
    op.drop_index(op.f('ix_merge_dismissal_name_a'), table_name='merge_dismissal')
    op.drop_table('merge_dismissal')
    # ### end Alembic commands ###
