"""add equipment, agenda, freezer capacity, batch days

Revision ID: e30464db9bc8
Revises: d769c4fc8f89
Create Date: 2026-08-31 19:33:10.274602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e30464db9bc8'
down_revision: Union[str, Sequence[str], None] = 'd769c4fc8f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: `suggestion.fridge_days` /
    # `suggestion.freezer_friendly` need server defaults so `ADD COLUMN ...
    # NOT NULL` doesn't fail against a SQLite file with existing `suggestion`
    # rows — same reasoning as `ffd7922d8ec7`. Pre-existing dishes predate
    # this self-reported estimate; `3` mirrors `Suggestion.fridge_days`'s own
    # dataclass default (see `app/domain/suggestion.py`), and `freezer_friendly`
    # defaults to the conservative `false`. ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_table('meal_plan_agenda_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('storage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_agenda_entry_meal_plan_id'), 'meal_plan_agenda_entry', ['meal_plan_id'], unique=False)
    op.add_column('fridge_input', sa.Column('days', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('freezer_capacity_slots', sa.Integer(), nullable=True))
    op.add_column('suggestion', sa.Column('fridge_days', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('suggestion', sa.Column('freezer_friendly', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestion', 'freezer_friendly')
    op.drop_column('suggestion', 'fridge_days')
    op.drop_column('settings', 'freezer_capacity_slots')
    op.drop_column('fridge_input', 'days')
    op.drop_index(op.f('ix_meal_plan_agenda_entry_meal_plan_id'), table_name='meal_plan_agenda_entry')
    op.drop_table('meal_plan_agenda_entry')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
