"""add agent run phase and proposed ideas

Revision ID: ffd7922d8ec7
Revises: d3aa8367395f
Create Date: 2026-08-27 07:29:39.077661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffd7922d8ec7'
down_revision: Union[str, Sequence[str], None] = 'd3aa8367395f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: `phase` needs a
    # server default so `ADD COLUMN ... NOT NULL` doesn't fail against a
    # SQLite file with existing `agent_run` rows. Pre-existing rows predate
    # the two-phase split and already represent finished (or in-flight)
    # recipe generation, so `'recipes'` is the closest fit — see the
    # project plan and `AgentRun.proposed_ideas_json`'s docstring. ###
    op.add_column(
        'agent_run',
        sa.Column(
            'phase',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='recipes',
        ),
    )
    op.add_column('agent_run', sa.Column('proposed_ideas_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_run', 'proposed_ideas_json')
    op.drop_column('agent_run', 'phase')
    # ### end Alembic commands ###
